### ISSUE TITLE
Running download_data_model.sh doesn't add a API_composite.json file in the data/standard_process/base folder

### ISSUE THREAD

**Issue by mkiourlappou** [batmen-lab/BioMANIA#3]
Hi, when I download the data from the google drive and then run the command `sh download_data_model.sh ` the base folder with the required json file doesn't appear. Therefore when I run the backend and frontend there is an error in the server and the chatbot doesn't provide any data back.

**Comment by DoraDong-2023** [comment]
Hi! Thank you for your attention and suggestions. We have updated the `Google Drive` and the `download_data_model.sh `file to include the base folder.  Would you mind trying it again and let us know if there are any other issues. We appreciate your patience and any suggestions!

**Comment by mkiourlappou** [comment]
Thank you very much for the quick reply and for updating the data on the Google Drive. I was able to run the chatbot but I got a `[TypeError: fetch failed] { cause: [Error: AggregateError] }` which I believe is related to a different issue related to my jaxlib version and my CPU/m3 apple chip not being compatible, as I see this error message: `RuntimeError: This version of jaxlib was built using AVX instructions, which your CPU and/or operating system do not support. You may be able work around this issue by building jaxlib from source.`

**Comment by DoraDong-2023** [comment]
Hi, thanks for the information provided. I have never encountered this issue before. I would recommend trying based on linux system, or we will provide a newer docker version 1.1.10 or newer colab demo later for you to try. Thanks!
