### ISSUE TITLE
Trying to connect but ....

### ISSUE THREAD

**Issue by AntonioBaeza** [batmen-lab/BioMANIA#4]
Wait a few minutes and refresh the page. If that still doesn't work, please contact the developer of this page for more information.

I refreshed multiple times, unfortunately, is not working

**Comment by DoraDong-2023** [comment]
Thanks for your attention!
Currently our demo is deployed stably on our server. Would you mind having a try again? Thanks for your patience

**Comment by AntonioBaeza** [comment]
Thank you, I will try again soon!
