### ISSUE TITLE
colab dependency error

### ISSUE THREAD

**Issue by inspirewind** [batmen-lab/BioMANIA#5]
> ERROR: Cannot install BioMANIA, biomania==0.1 and medcat because these package versions have conflicting dependencies.
> 
> The conflict is caused by:
>     biomania 0.1 depends on Requests==2.31.0
>     bionty 0.36.0 depends on requests
>     ehrapy 0.6.0 depends on requests
>     gradio 3.14.0 depends on requests
>     langchain 0.0.330 depends on requests<3 and >=2
>     pygithub 2.3.0 depends on requests>=2.14.0
>     tensorboard 2.15.1 depends on requests<3 and >=2.21.0
>     transformers 4.35.0 depends on requests
>     datasets 3.0.0 depends on requests>=2.32.2
>     biomania 0.1 depends on Requests==2.31.0
>     bionty 0.36.0 depends on requests
>     ehrapy 0.6.0 depends on requests
>     gradio 3.14.0 depends on requests
>     langchain 0.0.330 depends on requests<3 and >=2
>     pygithub 2.3.0 depends on requests>=2.14.0
>     tensorboard 2.15.1 depends on requests<3 and >=2.21.0
>     transformers 4.35.0 depends on requests
>     datasets 2.21.0 depends on requests>=2.32.2
>     biomania 0.1 depends on Requests==2.31.0
>     bionty 0.36.0 depends on requests
>     ehrapy 0.6.0 depends on requests
>     gradio 3.14.0 depends on requests
>     langchain 0.0.330 depends on requests<3 and >=2
>     pygithub 2.3.0 depends on requests>=2.14.0
>     tensorboard 2.15.1 depends on requests<3 and >=2.21.0
>     transformers 4.35.0 depends on requests
>     datasets 2.20.0 depends on requests>=2.32.2
>     biomania 0.1 depends on Requests==2.31.0
>     bionty 0.36.0 depends on requests
>     ehrapy 0.6.0 depends on requests
>     gradio 3.14.0 depends on requests
>     langchain 0.0.330 depends on requests<3 and >=2
>     pygithub 2.3.0 depends on requests>=2.14.0
>     tensorboard 2.15.1 depends on requests<3 and >=2.21.0
>     transformers 4.35.0 depends on requests
>     datasets 2.19.2 depends on requests>=2.32.1
> 
> To fix this you could try to:
> 1. loosen the range of package versions you've specified
> 2. remove package versions to allow pip to attempt to solve the dependency conflict
> 
> ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/topics/dependency-resolution/#dealing-with-dependency-conflicts

**Comment by DoraDong-2023** [comment]
Thank you for your attention! 
We've updated the requirements.txt to ensure a smooth installation process. At this stage, we recommend trying out the online demo or running the Python script locally. More platform-compatible versions will be available soon.
We appreciate your patience!
