### ISSUE TITLE
Unable to follow the tuto for converting R package  to your APP

### ISSUE THREAD

**Issue by BELKHIR** [batmen-lab/BioMANIA#6]
Thank you for sharing this App.

I tried to follow the tutorial available in blob/main/docs/R2APP.md but got many problems :
First the script get_API_init_from_sourcecode_R.py seems to be hardcoded for ggplot2.
Second I can't find the script prepare_retriever_data.py.
In the paragraph  "Train the model with this command" the LIB is set to scanpy.
In step 5 the LIB is set to ggplot2.
...

I'm aware that this part is under development  ...

Any chance to have a running tutorial ?

Many Thanks

Khalid,

**Comment by DoraDong-2023** [comment]
Thanks for your attention! 

Yes you are right, unfortunately R2APP is currently still under developing. 

I will drop you a note once this part is updated and R tutorial is prepared. Thanks again for your patience!
