### ISSUE TITLE
Error during Quick Start installation

### ISSUE THREAD

**Issue by mkojima123** [batmen-lab/BioMANIA#7]
Thank you for sharing this App.

I followed the installation instructions from https://github.com/batmen-lab/BioMANIA#setup-dataset-and-models, but I encountered an error.
I am using a Conda environment with Python 3.10 and pip 21.3.1.
```
INFO: This is taking longer than usual. You might need to provide the dependency resolver with stricter constraints to reduce runtime. See https://pip.pypa.io/warnings/backtracking for guidance. If you want to abort this run, press Ctrl + C.
INFO: This is taking longer than usual. You might need to provide the dependency resolver with stricter constraints to reduce runtime. See https://pip.pypa.io/warnings/backtracking for guidance. If you want to abort this run, press Ctrl + C.
  Downloading jax-0.4.27-py3-none-any.whl (1.9 MB)
     |████████████████████████████████| 1.9 MB 1.7 MB/s
  Downloading jax-0.4.26-py3-none-any.whl (1.9 MB)
     |████████████████████████████████| 1.9 MB 1.5 MB/s
ERROR: Exception:
Traceback (most recent call last):
  File "/home/biomania/python3.10_2/miniconda/lib/python3.10/site-packages/pip/_internal/cli/base_command.py", line 164, in exc_logging_wrapper
    status = run_func(*args)
  File "/home/biomania/python3.10_2/miniconda/lib/python3.10/site-packages/pip/_internal/cli/req_command.py", line 205, in wrapper
    return func(self, options, args)
  File "/home/biomania/python3.10_2/miniconda/lib/python3.10/site-packages/pip/_internal/commands/install.py", line 338, in run
    requirement_set = resolver.resolve(
  File "/home/biomania/python3.10_2/miniconda/lib/python3.10/site-packages/pip/_internal/resolution/resolvelib/resolver.py", line 92, in resolve
    result = self._result = resolver.resolve(
  File "/home/biomania/python3.10_2/miniconda/lib/python3.10/site-packages/pip/_vendor/resolvelib/resolvers.py", line 482, in resolve
    state = resolution.resolve(requirements, max_rounds=max_rounds)
  File "/home/biomania/python3.10_2/miniconda/lib/python3.10/site-packages/pip/_vendor/resolvelib/resolvers.py", line 393, in resolve
    raise ResolutionTooDeep(max_rounds)
pip._vendor.resolvelib.resolvers.ResolutionTooDeep: 2000000
```

Could you please advise me on how to successfully install it?

Thank you

**Comment by DoraDong-2023** [comment]
Thanks for your attention in BioMANIA! Sadly I couldn't repeat your error so I would only recommend some possible directions to try. 

- try 'python -m pip install --upgrade pip' to update pip version
- try under python=3.9 
- try on Linux device/ Ubuntu environment
- try Docker for local deployment or online demo for temporary trial

If you have any further info for locating the issue for discussion, feel free to copy and paste here. Thanks!

**Comment by mkojima123** [comment]
Thank you for your advice.

I attempted to upgrade pip, but I encountered the same error. The installation command I used is as follows:
```
pip install -r requirements.txt --index-url https://pypi.org/simple
```

Here are the versions of pip and Python I am using:
pip: 24.2
Python: 3.9.20

Could you please confirm if the installation command is correct? Thank you.

**Comment by DoraDong-2023** [comment]
Thanks for your reply. I try to repeat your case under both Linux and Mac device using the same command, unfortunately we didn't find the same error information. 

For your reference, here are some information

Our server is in Canada, my Ubuntu device information is 
```
Description:	Ubuntu 22.04.3 LTS
```
my mac device information is 
```
Kernel Version: Darwin 23.4.0
```
Both environment is under
```
Python: 3.9.20
Pip: 24.2
```

By the way, we have updated the requirements.txt file to include the least workable dependencies to ensure smooth and faster installation. We recommend trying `pip install -r requirements.txt` plus a mirror that is supported in your region.

Let us know if there exist further issues.
